embeddings {
  tensor_name: "verification/embedding:00000"
  metadata_path: "00000/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00000/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00000/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00001"
  metadata_path: "00001/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00001/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00001/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00002"
  metadata_path: "00002/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00002/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00002/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00003"
  metadata_path: "00003/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00003/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00003/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00004"
  metadata_path: "00004/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00004/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00004/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00005"
  metadata_path: "00005/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00005/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00005/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00006"
  metadata_path: "00006/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00006/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00006/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00007"
  metadata_path: "00007/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00007/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00007/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00008"
  metadata_path: "00008/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00008/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00008/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00009"
  metadata_path: "00009/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00009/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00009/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00010"
  metadata_path: "00010/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00010/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00010/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00011"
  metadata_path: "00011/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00011/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00011/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00012"
  metadata_path: "00012/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00012/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00012/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00013"
  metadata_path: "00013/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00013/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00013/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00014"
  metadata_path: "00014/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00014/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00014/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00015"
  metadata_path: "00015/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00015/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00015/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00016"
  metadata_path: "00016/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00016/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00016/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00017"
  metadata_path: "00017/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00017/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00017/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00018"
  metadata_path: "00018/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00018/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00018/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00019"
  metadata_path: "00019/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00019/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00019/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00020"
  metadata_path: "00020/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00020/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00020/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00021"
  metadata_path: "00021/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00021/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00021/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00022"
  metadata_path: "00022/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00022/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00022/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00023"
  metadata_path: "00023/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00023/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00023/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00024"
  metadata_path: "00024/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00024/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00024/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00025"
  metadata_path: "00025/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00025/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00025/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00026"
  metadata_path: "00026/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00026/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00026/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00027"
  metadata_path: "00027/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00027/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00027/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00028"
  metadata_path: "00028/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00028/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00028/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00029"
  metadata_path: "00029/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00029/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00029/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00030"
  metadata_path: "00030/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00030/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00030/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00031"
  metadata_path: "00031/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00031/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00031/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00032"
  metadata_path: "00032/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00032/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00032/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00033"
  metadata_path: "00033/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00033/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00033/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00034"
  metadata_path: "00034/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00034/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00034/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00035"
  metadata_path: "00035/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00035/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00035/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00036"
  metadata_path: "00036/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00036/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00036/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00037"
  metadata_path: "00037/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00037/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00037/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00038"
  metadata_path: "00038/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00038/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00038/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00039"
  metadata_path: "00039/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00039/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00039/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00040"
  metadata_path: "00040/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00040/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00040/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00041"
  metadata_path: "00041/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00041/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00041/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00042"
  metadata_path: "00042/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00042/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00042/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00043"
  metadata_path: "00043/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00043/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00043/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00044"
  metadata_path: "00044/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00044/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00044/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00045"
  metadata_path: "00045/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00045/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00045/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00046"
  metadata_path: "00046/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00046/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00046/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00047"
  metadata_path: "00047/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00047/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00047/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00048"
  metadata_path: "00048/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00048/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00048/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00049"
  metadata_path: "00049/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00049/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00049/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00050"
  metadata_path: "00050/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00050/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00050/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00051"
  metadata_path: "00051/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00051/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00051/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00052"
  metadata_path: "00052/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00052/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00052/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00053"
  metadata_path: "00053/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00053/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00053/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00054"
  metadata_path: "00054/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00054/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00054/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00055"
  metadata_path: "00055/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00055/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00055/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00056"
  metadata_path: "00056/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00056/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00056/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00057"
  metadata_path: "00057/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00057/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00057/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00058"
  metadata_path: "00058/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00058/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00058/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00059"
  metadata_path: "00059/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00059/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00059/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00060"
  metadata_path: "00060/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00060/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00060/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00061"
  metadata_path: "00061/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00061/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00061/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00062"
  metadata_path: "00062/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00062/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00062/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00063"
  metadata_path: "00063/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00063/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00063/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00064"
  metadata_path: "00064/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00064/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00064/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00065"
  metadata_path: "00065/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00065/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00065/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00066"
  metadata_path: "00066/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00066/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00066/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00067"
  metadata_path: "00067/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00067/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00067/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00068"
  metadata_path: "00068/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00068/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00068/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00069"
  metadata_path: "00069/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00069/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00069/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00070"
  metadata_path: "00070/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00070/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00070/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00071"
  metadata_path: "00071/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00071/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00071/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00072"
  metadata_path: "00072/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00072/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00072/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00073"
  metadata_path: "00073/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00073/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00073/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00074"
  metadata_path: "00074/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00074/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00074/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00075"
  metadata_path: "00075/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00075/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00075/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00076"
  metadata_path: "00076/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00076/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00076/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00077"
  metadata_path: "00077/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00077/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00077/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00078"
  metadata_path: "00078/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00078/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00078/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00079"
  metadata_path: "00079/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00079/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00079/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00080"
  metadata_path: "00080/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00080/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00080/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00081"
  metadata_path: "00081/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00081/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00081/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00082"
  metadata_path: "00082/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00082/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00082/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00083"
  metadata_path: "00083/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00083/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00083/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00084"
  metadata_path: "00084/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00084/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00084/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00085"
  metadata_path: "00085/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00085/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00085/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00086"
  metadata_path: "00086/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00086/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00086/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00087"
  metadata_path: "00087/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00087/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00087/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00088"
  metadata_path: "00088/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00088/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00088/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00089"
  metadata_path: "00089/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00089/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00089/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00090"
  metadata_path: "00090/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00090/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00090/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00091"
  metadata_path: "00091/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00091/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00091/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00092"
  metadata_path: "00092/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00092/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00092/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00093"
  metadata_path: "00093/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00093/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00093/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00094"
  metadata_path: "00094/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00094/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00094/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00095"
  metadata_path: "00095/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00095/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00095/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00096"
  metadata_path: "00096/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00096/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00096/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00097"
  metadata_path: "00097/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00097/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00097/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00098"
  metadata_path: "00098/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00098/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00098/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00099"
  metadata_path: "00099/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00099/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00099/verification%2fembedding\\tensors.tsv"
}
